import React from 'react'
class BUTTON extends React.Component {
    constructor(props){
        super(props)
    }
    render(){
        return (
            <div className='buttons'>
                <button 
                    id="clear"
                    value='AC'
                    onClick={this.props.clear}
                >
                 AC
                </button>
                <button 
                    className='operations'
                    id="divide"
                    value='/'
                    onClick={this.props.chooseOperation}
                >
                 /
                </button>
                <button 
                    className='operations'
                    id="multiply"
                    value='*'
                    onClick={this.props.chooseOperation}
                >
                 X
                </button>
                <button 
                    id="seven"
                    value='7'
                    onClick={this.props.appendNumber}
                >
                 7
                </button>
                <button 
                    id="eight"
                    value='8'
                    onClick={this.props.appendNumber}
                >
                 8
                </button>
                <button 
                    id="nine"
                    value='9'
                    onClick={this.props.appendNumber}
                >
                 9
                </button>
                <button 
                    className='operations'
                    id="subtract"
                    value='-'
                    onClick={this.props.chooseOperation}
                >
                 -
                </button>
                <button 
                    id="four"
                    value='4'
                    onClick={this.props.appendNumber}
                >
                 4
                </button>
                <button 
                    id="five"
                    value='5'
                    onClick={this.props.appendNumber}
                >
                 5
                </button>
                <button 
                    id="six"
                    value='6'
                    onClick={this.props.appendNumber}
                >
                 6
                </button>
                <button 
                    className='operations'
                    id="add"
                    value='+'
                    onClick={this.props.chooseOperation}
                >
                 +
                </button>
                <button 
                    id="one"
                    value='1'
                    onClick={this.props.appendNumber}
                >
                 1
                </button>
                <button 
                    id="two"
                    value='2'
                    onClick={this.props.appendNumber}
                >
                 2
                </button>
                <button 
                    id="three"
                    value='3'
                    onClick={this.props.appendNumber}
                >
                 3
                </button>
                <button 
                    id="equals"
                    value='='
                    onClick={this.props.compute}
                >
                 =
                </button>
                <button 
                    id="zero"
                    value='0'
                    onClick={this.props.appendNumber}
                >
                 0
                </button>
                <button 
                    id="decimal"
                    value='.'
                    onClick={this.props.decimal}
                >
                 .
                </button>
                
            </div>
        );
    }
    
} 
export default BUTTON;